version: '3.9'

services:

  postgres:
    image: 'postgres:16'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_DB}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_DB}'
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'

volumes:
  postgres_data: