# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main', '**']
  pull_request:
    branches: ['main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean install node packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate key-pair
        run: ./generate-keys.sh

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start test containers and run migrations
        run: ./integration-starter.sh

      - name: Run tests
        run: npm test

      - name: Tear down Docker services
        if: always()
        run: docker compose -f test-compose.yml down
