name: CD Deploy to Azure Staging

on:
  push:
    branches: ['main', '**']
  pull_request:
    branches: ['main' ]


env:
  AZURE_APP_SERVICE_NAME_STAGING: 'hackin2-api-stg'
  AZURE_RESOURCE_GROUP: 'hackin2'
  DOCKER_IMAGE_NAME: 'hackin2-api'

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NAME_STAGING }}
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
