name: CD Deploy to Azure Production

on:
  push:
    branches:
      - main

env:
  AZURE_APP_SERVICE_NAME_PROD: 'hackin2-api-prd'
  AZURE_RESOURCE_GROUP: 'hackin2'
  DOCKER_IMAGE_NAME: 'hackin2-api'

jobs:
  build-and-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NAME_PROD }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest
