# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main', 'dev', 'feat/programs-view']
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean install node packages
        run: npm ci
      - name: Build
        run: npm run build

  container-setup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker compose up
        run: docker-compose -f test-compose.yml up -d
      - name: Copy .env.test to .env for testing
        run: cp .env.test -r .env
      - name: Push Prisma changes to the test database
        run: npx prisma db push

  test:
    runs-on: ubuntu-latest
    needs: container-setup
    steps:
      - name: Run tests
        run: npm test
      - name: Tear down Docker services
        if: always()
        run: docker-compose -f test-compose.yml down
